ADD: OAuth
deepringing/ssom-server pull request #2
Opened 2023-03-15 08:10 UTC by YuLim2

## 📄 Summary
> For google auth

<br>

## 🔨 Tasks
- AccessToken
- RefreshToken
- JWT
- SecurityConfig

<br>

## 🙋🏻 More

2023-03-15 08:13 UTC, gimhanul requested changes
? node module 뭐죠?

2023-03-15 10:02 UTC, gimhanul requested changes

2023-03-15 10:02 UTC, gimhanul commented on package.json
지우시구여

2023-03-15 10:02 UTC, gimhanul commented on yarn.lock
이것독

2023-03-15 23:54 UTC, gimhanul commented on src/main/java/com/ullim/ssomserver/domain/auth/presentation/dto/response/TokenResponse.java
> +    private Long roleId;
이건 어디에 쓰나여

2023-03-15 23:54 UTC, gimhanul commented on src/main/java/com/ullim/ssomserver/domain/user/domain/type/Authority.java
> +    private final String role;
쏨에는 학생이랑 선생ㄴ 권한 필요없지않나여

2023-03-15 23:54 UTC, gimhanul commented on src/main/java/com/ullim/ssomserver/global/error/ErrorResponse.java
> +}
방금 심청이 서버에 하고온 짓인데 code field 추가해서 error code 도 넣어주셍
ErrorProperty에 name() 함수 추가해서 긁어오면 댐ㄴ디ㅏ

2023-03-15 23:54 UTC, gimhanul commented on src/main/java/com/ullim/ssomserver/domain/auth/presentation/dto/response/TokenResponse.java
> +    private Long roleId;
roleId 말하는 것임

2023-03-15 23:59 UTC, YuLim2 commented on src/main/java/com/ullim/ssomserver/domain/auth/presentation/dto/response/TokenResponse.java
> +    private Long roleId;
ㅎ 실수입니다.

2023-03-16 08:10 UTC, gimhanul approved these changes

2023-03-16 08:14 UTC, merged